const fs=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const {parseHTML}=require(process.env.DOM_TEST_LIBRARY || 'linkedom');
const storage=new Map();
function page(name,query='') {
 const {window}=parseHTML(fs.readFileSync(name,'utf8'));
 const document=window.document;
 window.localStorage={getItem:key=>storage.get(key)||null,setItem:(key,value)=>storage.set(key,value)};
 window.location={href:name,search:query};
 window.URLSearchParams=URLSearchParams;
 window.requestAnimationFrame=callback=>callback();
 window.matchMedia=()=>({matches:false});
 window.testIntervals=[];
 window.setInterval=(callback,delay)=>{window.testIntervals.push({callback,delay});return window.testIntervals.length;};
 window.HTMLElement.prototype.scrollIntoView=function(){};
 window.HTMLElement.prototype.focus=function(){};
 window.HTMLElement.prototype.reportValidity=function(){return true;};
 window.HTMLElement.prototype.showModal=function(){this.open=true;};
 window.HTMLElement.prototype.close=function(){this.open=false;};
 window.fetch=()=>Promise.reject(new Error('No network in tests'));
 const context=vm.createContext(window);
 const scripts=[...document.querySelectorAll('script[src]')];
 const order=[...scripts.filter(s=>s.hasAttribute('defer')),...scripts.filter(s=>!s.hasAttribute('defer'))];
 for(const script of order)vm.runInContext(fs.readFileSync(script.getAttribute('src'),'utf8'),context,{filename:script.getAttribute('src')});
 function click(selector){const element=document.querySelector(selector);assert.ok(element,'Missing control '+selector);element.dispatchEvent(new window.Event('click',{bubbles:true,cancelable:true}));}
 function event(selector,type){document.querySelector(selector).dispatchEvent(new window.Event(type,{bubbles:true,cancelable:true}));}
 return {window,document,click,event};
}
let p=page('shop.html');
assert.equal(p.document.querySelectorAll('#product-grid .product-card').length,4);
p.click('#product-grid .cart-btn');
assert.equal(JSON.parse(storage.get('cart'))[0].quantity,1);
assert.equal(p.document.querySelector('#cart-count').textContent,'1');
p.document.querySelector('.search-container input').value='future';p.event('.search-container input','input');
assert.equal(p.document.querySelectorAll('#product-grid .product-card').length,1);
p.click('.shop-filter button:nth-child(2)');
assert.equal(p.document.querySelectorAll('#product-grid .product-card').length,0,'Search and category must combine');
p.document.querySelector('.search-container input').value='';p.event('.search-container input','input');
assert.equal(p.document.querySelectorAll('#product-grid .product-card').length,3);
p=page('cart.html');assert.match(p.document.querySelector('#cart-items').textContent,/Steps to Christ/);
p.click('#cart-items button[aria-label^="Increase"]');assert.equal(JSON.parse(storage.get('cart'))[0].quantity,2);assert.equal(p.document.querySelector('#grand-total').textContent,'$19.98');
p.click('#cart-items button[aria-label^="Decrease"]');assert.equal(JSON.parse(storage.get('cart'))[0].quantity,1);
p=page('product.html','?id=2');assert.equal(p.document.querySelector('#product-title').textContent,'God Predicts Your Future');
p.click('.quantity-controls button:last-child');p.click('#product-cart-btn');assert.equal(JSON.parse(storage.get('cart'))[1].quantity,2);
p.click('#buy-now-btn');assert.equal(p.window.location.href,'checkout.html');assert.equal(JSON.parse(storage.get('cart')).length,2,'Buy Now preserves existing cart');
p=page('product.html','?id=invalid');assert.match(p.document.querySelector('.product-details').textContent,/Select a resource/);
p=page('checkout.html');assert.match(p.document.querySelector('#checkout-items').textContent,/God Predicts/);
p.event('#checkout-form','submit');assert.match(p.window.location.href,/^mailto:/);assert.match(decodeURIComponent(p.window.location.href),/No payment has been made/);assert.equal(JSON.parse(storage.get('cart')).length,2);
p=page('contact.html');p.document.querySelector('form.contact-form input').value='Test name';p.event('form.contact-form','submit');assert.match(p.window.location.href,/^mailto:/);
p=page('donate.html');p.click('.amount-grid button:nth-child(2)');assert.equal(p.document.querySelector('.donation-amounts input').value,'25');p.click('.donation-card button');p.click('#donation-request');assert.match(decodeURIComponent(p.window.location.href),/USD 25.00/);
p=page('watch.html');p.click('.podcast-card button');assert.match(p.document.querySelector('.action-status').textContent,/not been provided/);
p=page('landmarks.html');p.click('[data-unavailable]');assert.match(p.document.querySelector('.action-status').textContent,/PDF/);
p=page('about.html');p.click('.glass-menu-toggle');assert.equal(p.document.querySelector('.glass-menu-toggle').getAttribute('aria-expanded'),'true');p.click('.glass-search-toggle');assert.equal(p.document.querySelectorAll('.glass-search-results a').length,9);p.document.querySelector('#glass-search-input').value='donate';p.event('#glass-search-input','input');assert.equal(p.document.querySelectorAll('.glass-search-results a').length,1);
p=page('bible-study.html');p.click('[data-study="old"]');assert.equal(p.document.querySelector('.lesson-dialog').open,true);p.click('#next-study');assert.equal(p.document.querySelector('#feature-title').textContent,'Growing in Faith');
p=page('bible-study.html');
assert.equal(p.window.testIntervals[0].delay,2000);
const tick=p.window.testIntervals[0].callback;
tick();assert.equal(p.document.querySelector('#feature-title').textContent,'Growing in Faith');
tick();tick();tick();assert.equal(p.document.querySelector('#feature-title').textContent,'The Life of Jesus');
p.event('.featured-study','mouseenter');tick();assert.equal(p.document.querySelector('#feature-title').textContent,'The Life of Jesus');
p.event('.featured-study','mouseleave');tick();assert.equal(p.document.querySelector('#feature-title').textContent,'Growing in Faith');
p.click('#start-feature');tick();assert.equal(p.document.querySelector('#feature-title').textContent,'Growing in Faith');
p=page('index.html');p.click('.menu-toggle');assert.equal(p.document.querySelector('.menu-toggle').getAttribute('aria-expanded'),'true');
p=page('order-success.html');assert.match(p.document.querySelector('.success-box h1').textContent,/unavailable/);
storage.set('cart','broken json');p=page('cart.html');assert.match(p.document.querySelector('#cart-items').textContent,/empty/);
storage.set('cart',JSON.stringify([{id:1,title:'<img src=x onerror=alert(1)>',price:0.01,image:'https://evil.invalid/track',quantity:2},{id:999,price:1,title:'Fake product',quantity:1}]));
p=page('cart.html');
assert.equal(p.document.querySelector('#grand-total').textContent,'$19.98');
assert.doesNotMatch(p.document.querySelector('#cart-items').innerHTML,/onerror|evil\.invalid|Fake product/);
p=page('watch.html');assert.equal(p.document.querySelector('iframe').getAttribute('src'),null);
p.click('.cookie-actions button:last-child');assert.match(p.document.querySelector('iframe').getAttribute('src'),/youtube-nocookie/);
p.click('.cookie-settings');p.click('.cookie-actions button:first-child');assert.equal(p.document.querySelector('iframe').getAttribute('src'),null);
console.log('Passed: shop search/filtering, cart persistence and totals, product quantities and Buy Now, email inquiry flows, media/PDF availability, navigation, Bible study previews, malformed storage, and honest order status.');
